sudo: required
services:
  -docker

before_install: #before our tests are run
  - docker build -t m4r14r1os/course-docker-react -f Dockerfile.dev .  #In Dockerfile.dev the tests are generated.

script:
  - docker run -e CI=true m4r14r1os/course-docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-course-react-aws"
  env: "Docker-course-react-aws-env"
  bucket_name: "elasticbeanstalk-us-east-2-289913794490"
  bucket_path: "docker-course-react-aws"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
